# Generated by Django 4.0.2 on 2022-04-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('technicalskill', models.CharField(blank=True, max_length=500, null=True)),
                ('workexperience', models.CharField(blank=True, max_length=200, null=True)),
                ('courses', models.CharField(blank=True, max_length=200, null=True)),
                ('projects', models.CharField(blank=True, max_length=200, null=True)),
                ('awards', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('educationdetail', models.TextField(blank=True, null=True)),
                ('careerobjective', models.TextField(blank=True, null=True)),
                ('other', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
